### PR TITLE
[0.6] Laravel 10 and 11 support

### PR DESCRIPTION
**Pull request by ItprojektRepo**
- Laravel 10 support
- Laravel 11 support
- PHPUnit 11 support
- Orchestra Testbench 9 support
- Remove PHP 7.x support

### CODE REVIEW

**Comment by pierrekttipay** [comment]
@clemblanco @oaklees please accept this PR so we can upgrade our laravel to v11 while still using laravel-aws-pubsub, please.

**Comment by pierrekttipay** [comment]
Thanks @clemblanco for working so hard on this! 
Much appreciated.

**Review by oaklees — APPROVED** [review]

**Comment by clemblanco** [comment]
Glad people are using our package @pierrekttipay 

Can you expend a bit more on how you use it, what for and how do you find it so far?

**Comment by ojhaujjwal** [comment]
Thanks for quickly actioning the request to review folks @clemblanco @oaklees. I will reply on behalf of @pierrekttipay with whom I work at https://kttipay.com/.

We use this package for integrating with AWS EventBridge as the broker for event driven architecture in order to de-couple the modules in our system. 

This package is a perfect fit in the sense that it has a very minimal footprint and is based on the very awesome Laravel's broadcasting setup and ease of usage via the Laravel's event dispatcher.

Initially, we used Laravel's event dispatcher as in-memory event broker without event bridge. However, we wanted a more reliable listener retry mechanism in case the listener fails and event bridge is great at that. All the event listeners are [API Destination](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-api-destinations.html#:~:text=Amazon%20EventBridge%20API%20destinations%20are%20HTTP%20endpoints%20that,an%20AWS%20service%20or%20resource%20as%20a%20target.) (pointing to the same Laravel app) with suitable retry configured and a Dead-Letter-Queue SQS for each listener configured if an event listener can't respond with 200 after continuous retries.

I hope that makes sense.

**Pull request merged**
